"""
Shared profanity word list - curse, sexual, abusive, adultery, f-words, obscene language
Used by both audio_profanity_detector.py and subtitle_processor.py
"""

# Comprehensive profanity list - curse, sexual, abusive, adultery, f-words, obscene language
# Note: "damn" and variations are NOT included as they are not considered obscene
PROFANITY_WORDS = {
    # F-words and variations
    'fuck', 'fucking', 'fucked', 'fucker', 'fuckers', 'fuckin', 'fucka', 'fuckable', 'fuckass',
    'fuckbag', 'fuckbitch', 'fuckbook', 'fuckboy', 'fuckbrain', 'fuckbuddy', 'fuckbutt',
    'fuckd', 'fuckedup', 'fuckersucker', 'fuckface', 'fuckfest', 'fuckfreak', 'fuckfriend',
    'fuckhead', 'fuckheads', 'fuckher', 'fuckhole', 'fuckina', 'fuckings', 'fuckingshitmotherfucker',
    'fuckinnuts', 'fuckinright', 'fuckit', 'fuckknob', 'fuckme', 'fuckmeat', 'fuckmehard',
    'fuckmonkey', 'fuckn', 'fucknugget', 'fucknut', 'fucknuts', 'fucknutt', 'fucknutz',
    'fuckoff', 'fuckpig', 'fuckpuppet', 'fuckr', 'fucks', 'fuckstick', 'fucktard', 'fucktards',
    'fucktoy', 'fucktrophy', 'fuckup', 'fuckwad', 'fuckwhit', 'fuckwhore', 'fuckwit', 'fuckwitt',
    'fuckyomama', 'fuckyou', 'fuk', 'fukah', 'fuken', 'fuker', 'fukin', 'fuking', 'fukk',
    'fukkah', 'fukken', 'fukker', 'fukkin', 'fukking', 'fuks', 'fuktard', 'fuktards',
    'fukwhit', 'fukwit', 'fuuck', 'fux', 'fux0r', 'fuxor', 'fvck', 'fvk', 'fxck',
    # Shit words and variations
    'shit', 'shitting', 'shitty', 'shits', 'shitbox', 'shitcan', 'shitdick', 'shite',
    'shiteater', 'shited', 'shitface', 'shitfaced', 'shitfit', 'shitforbrains', 'shitfuck',
    'shitfucker', 'shitfull', 'shithapens', 'shithappens', 'shithead', 'shithouse', 'shiting',
    'shitlist', 'shitola', 'shitoutofluck', 'shitstain', 'shitted', 'shitter', 'bullshit',
    'bullshits', 'bullshitted', 'horseshit',
    # Ass words and variations
    'ass', 'asses', 'asshole', 'assholes', 'assbag', 'assbagger', 'assbandit', 'assbang',
    'assbanged', 'assbanger', 'assbangs', 'assbite', 'assblaster', 'assclown', 'asscock',
    'asscowboy', 'asscracker', 'assface', 'assfuck', 'assfucker', 'assfukka', 'assgoblin',
    'assh0le', 'assh0lez', 'asshat', 'asshead', 'assho1e', 'assholz', 'asshopper', 'asshore',
    'assjacker', 'assjockey', 'asskiss', 'asskisser', 'assklown', 'asslick', 'asslicker',
    'asslover', 'assman', 'assmaster', 'assmonkey', 'assmunch', 'assmuncher', 'assnigger',
    'asspacker', 'asspirate', 'asspuppies', 'assrammer', 'assranger', 'assshit', 'assshole',
    'asssucker', 'asswad', 'asswhole', 'asswhore', 'asswipe', 'asswipes', 'azz', 'azzhole',
    'bigass', 'dumbass', 'dumbasses', 'fatass', 'gassyass', 'gayass', 'smartass',
    # Bitch words and variations
    'bitch', 'bitches', 'bitching', 'bitchass', 'bitched', 'bitcher', 'bitchers', 'bitchez',
    'bitchin', 'bitchslap', 'bitchtit', 'bitchy', 'biteme', 'dumbbitch', 'nastybitch',
    'skankbitch', 'skankybitch',
    # Hell variations (damn removed - not obscene)
    'hell', 'hells', 'he11',
    # Bastard variations
    'bastard', 'bastards', 'bast', 'bastardo', 'bastardz', 'bassterd', 'bassterds',
    'basterds', 'basterdz', 'bigbastard',
    # Crap and piss
    'crap', 'crappy', 'crapola', 'crapper', 'piss', 'pissing', 'pissed', 'pisser', 'pisses',
    'pisshead', 'pissin', 'pissoff',
    # Dick words and variations
    'dick', 'dicks', 'dickhead', 'dick pic', 'dick-ish', 'dickbag', 'dickbeater', 'dickbeaters',
    'dickbrain', 'dickdipper', 'dickface', 'dickflipper', 'dickforbrains', 'dickfuck',
    'dickheads', 'dickhole', 'dickish', 'dickjuice', 'dickless', 'dicklick', 'dicklicker',
    'dickman', 'dickmilk', 'dickmonger', 'dickpic', 'dickripper', 'dicksipper', 'dickslap',
    'dickslicker', 'dicksucker', 'dickwad', 'dickweasel', 'dickweed', 'dickwhipper', 'dickwod',
    'dickzipper', 'pindick', 'limpdick',
    # Cock words and variations
    'cock', 'cocks', 'cock-head', 'cock-sucker', 'cockbite', 'cockblock', 'cockblocker',
    'cockburger', 'cockcowboy', 'cockface', 'cockfight', 'cockfucker', 'cockhead', 'cockholster',
    'cockjockey', 'cockknob', 'cockknocker', 'cockknoker', 'cocklicker', 'cocklover',
    'cockmaster', 'cockmongler', 'cockmongruel', 'cockmonkey', 'cockmunch', 'cockmuncher',
    'cocknob', 'cocknose', 'cocknugget', 'cockqueen', 'cockrider', 'cockshit', 'cocksman',
    'cocksmith', 'cocksmoker', 'cocksucer', 'cocksuck', 'cocksucked', 'cocksucker',
    'cocksucking', 'cocksucks', 'cocksuka', 'cocksukka', 'cocktease', 'cocktail', 'cocky',
    'c0ck', 'c0cks', 'c0cksucker', 'c0k', 'cawk', 'cawks', 'cazzo', 'cok', 'cokmuncher',
    'coksucka', 'kock',
    # Pussy words and variations
    'pussy', 'pussies', 'puss', 'pussie', 'pussycat', 'pussyeater', 'pussyfucker',
    'pussylicker', 'pussylips', 'pussylover', 'pussypounder', 'pusy', 'pu55i', 'pu55y',
    'hotpussy', 'destroyyourpussy',
    # Cunt words and variations
    'cunt', 'cunts', 'cunteyed', 'cuntface', 'cuntfuck', 'cuntfucker', 'cunthole',
    'cunthunter', 'cuntlick', 'cuntlicker', 'cuntlicking', 'cuntrag', 'cuntslut',
    'cuntsucker', 'cuntz', 'cnut', 'cnts', 'cntz', 'cunilingus', 'cunillingus', 'cunn',
    'cunnie', 'cunnilingus', 'cunntt', 'cunny', 'kunilingus', 'kunnilingus', 'kunt', 'kunts',
    'kuntz',
    # Whore words and variations
    'whore', 'whores', 'asswhore', 'crackwhore', 'fuckwhore', 'nastywhore', 'sexwhore',
    'skankwhore', 'skankywhore', 'slutwhore', 'whorefucker', 'whorehouse', 'camwhore',
    'easyslut', 'nastyslut',
    # Slut words and variations
    'slut', 'sluts', 'slutt', 'slutting', 'slutty', 'slutwear', 'slutwhore',
    # Motherfucker variations
    'motherfucker', 'motherfuckers', 'motherfuck', 'motherfucked', 'motherfuckin',
    'motherfucking', 'motherfuckings', 'mothafuck', 'mothafucka', 'mothafuckaz', 'mothafucked',
    'mothafucker', 'mothafuckin', 'mothafucking', 'mothafuckings', 'mofo', 'm0f0', 'm0fo',
    # Sexual references and body parts
    'sperm', 'semen', 'cum', 'cum face', 'cum licker', 'cumbubble', 'cumdumpster', 'cumfest',
    'cumguzzler', 'cuming', 'cumjockey', 'cumlickr', 'cumm', 'cummer', 'cummin', 'cumming',
    'cumquat', 'cumqueen', 'cums', 'cumshot', 'cumshots', 'cumslut', 'cumstain', 'cumsucker',
    'cumtart', 'kum', 'kumbubble', 'kumbullbe', 'kumer', 'kummer', 'kumming', 'kumquat',
    'kums', 'jiz', 'jizim', 'jizin', 'jizjuice', 'jizm', 'jizn', 'jizz', 'jizzd', 'jizzed',
    'jizzim', 'jizzin', 'jizzn', 'jizzum', 'jism', 'jiss', 'jisim',
    'sex', 'sexual', 'sexually', 'sexed', 'sexfarm', 'sexhound', 'sexhouse', 'sexing',
    'sexkitten', 'sexpot', 'sexslave', 'sextogo', 'sextoy', 'sextoys', 'sexwhore', 'sexy',
    'sexymoma', 'sexymoma', 'sexy-slim', 'cybersex', 'gay sex', 'gaysex', 'group sex',
    'hardcoresex', 'hotsex', 'livesex', 'phonesex',
    'porn', 'pornography', 'pornographic', 'pornflick', 'pornking', 'porno', 'pornprincess',
    'nude', 'naked', 'nudity', 'nudger', 'barenaked',
    'orgasm', 'orgasmic', 'orga', 'orgasim', 'orgies', 'orgy', 'goregasm',
    'masturbat', 'masturbation', 'masturbating', 'm45terbate', 'ma5terb8', 'ma5terbate',
    'massterbait', 'masstrbait', 'masstrbate', 'mastabate', 'mastabater', 'master-bate',
    'masterb8', 'masterbaiter', 'masterbat', 'masterbat3', 'masterbate', 'masterblaster',
    'mastrabator', 'beatoff', 'beatyourmeat', 'jerk off', 'jerk-off', 'jerk0ff', 'jerked',
    'jerkoff', 'j3rk0ff', 'jack off', 'jack-off', 'jackoff', 'smackthemonkey', 'spankthemonkey',
    'ejaculat', 'ejaculation', 'ejackulate', 'ejakulate',
    'penis', 'vagina', 'genital', 'genitals', 'peni5', 'penile', 'penises', 'vaginal',
    'breast', 'breasts', 'boob', 'boobs', 'boobies', 'booby', 'b00b', 'b00bies', 'b00biez',
    'b00bs', 'b00bz', 'booobs', 'boooobs', 'booooobs', 'booooooobs', 'brea5t', 'breastjob',
    'breastlover', 'breastman', 'big breasts', 'big knockers', 'big tits', 'bigbreasts',
    'bigtits', 'bitties', 'dirty pillows', 'headlights', 'knockers', 'mams', 'tits', 'titties',
    'tit', 'titbitnipply', 'titfuck', 'titfucker', 'titfuckin', 'titjob', 'titlicker',
    'titlover', 'titty', 'tittie',
    'butt', 'buttock', 'buttocks', 'butt plug', 'butt-pirate', 'buttbang', 'buttcheeks',
    'buttface', 'buttfuck', 'buttfucker', 'buttfuckers', 'butthead', 'butthole', 'buttman',
    'buttmuch', 'buttmunch', 'buttmuncher', 'buttpirate', 'buttplug', 'buttstain', 'buttwipe',
    'bigbutt', 'rearend', 'rump',
    'nipple', 'nipplering', 'clit', 'clitface', 'clitfuck', 'clits', 'clitty', 'cl1t',
    'labia', 'hymen', 'rectum', 'scrotum', 'teste', 'testicle', 'testicles', 'gonad', 'gonads',
    'glans', 'foreskin', 'crotch', 'crotchjockey', 'crotchmonkey', 'crotchrot',
    # Sexual activity and intimate scenes
    'kiss', 'kissing', 'kissed', 'kisses', 'kissass',
    'foreplay', 'intimate', 'intimacy',
    'lovemaking', 'make love', 'making love', 'getiton', 'laid',
    'intercourse', 'sexual intercourse', 'coital', 'coitus', 'copulate', 'fornicate',
    'oral sex', 'anal sex', 'analsex', 'anilingus', 'cunnilingus', 'fellatio', 'felatio',
    'felch', 'felcher', 'felching', 'fellate', 'feltch', 'feltcher', 'feltching',
    'deep throat', 'deep throating', 'deapthroat', 'deepthroat', 'deepthroating',
    'blow j', 'blow job', 'blow your l', 'blow your load', 'blowjob', 'blowjobs', 'givehead',
    'hand job', 'handjob', 'footjob', 'rimjob', 'rimming',
    'moan', 'moaning', 'groan', 'groaning', 'female squirting', 'femalesquirtin',
    'femalesquirting', 'male squirting',
    'erotic', 'erotica', 'eroticism', 'ero', 'earotics', 'auto erotic', 'autoerotic',
    'bondage', 'bdsm', 'dominatricks', 'dominatrics', 'dominatrix', 'dommes', 'masochist',
    'masokist', 'sadis', 'sadom', 'fetish', 'foot fetish', 'footaction', 'footfetish',
    'footfuck', 'footfucker', 'footlicker', 'footstar',
    'seduce', 'seduction', 'seductive',
    'bedroom', 'bed scene', 'bedroom scene', 'shower scene', 'bath scene',
    'stripper', 'stripping', 'strip club', 'stripclub',
    'lingerie', 'underwear', 'bra', 'panties', 'panti', 'gstring',
    'suggestive', 'suggestively',
    'flirt', 'flirting', 'flirtatious',
    'threesome', 'threeway', 'foursome', 'gang bang', 'gangbang', 'gangbanged', 'gangbanger',
    'gangbangs', 'double penetration', 'doublepenetration', 'dp action', 'dpaction',
    'bareback', 'barely legal', 'barelylegal',
    'creamy', 'creampie', 'pearlnecklace', 'golden shower', 'goldenshower', 'brown shower',
    'brown showers',
    'dog style', 'dog-fucker', 'doggie style', 'doggie', 'doggie-style', 'doggiestyle',
    'doggin', 'dogging', 'doggy style', 'doggy-style', 'doggystyle', 'dawgie style',
    'dawgie-style',
    'dildo', 'dildos', 'dild0', 'dild0s', 'd1ld0', 'd1ldo', 'dilld0', 'dilld0s',
    'vibr', 'vibrater', 'vibrator', 'bullet vibe', 'magicwand',
    'fingerbang', 'fingerfood', 'fingerfuck', 'fingerfucked', 'fingerfucker', 'fingerfuckers',
    'fingerfucking', 'fingerfucks', 'fingering',
    'fisted', 'fister', 'fistfuck', 'fistfucked', 'fistfucker', 'fistfuckers', 'fistfucking',
    'fistfuckings', 'fistfucks', 'fisting', 'fisty',
    'frotting', 'spank',
    'queef', 'wetspot',
    # Adultery and cheating related
    'cheat', 'cheating', 'cheater', 'adultery', 'adulterous', 'affair', 'infidelity',
    'unfaithful', 'betrayal', 'betray',
    # Obscene and vulgar terms
    'turd', 'poop', 'pooper', 'pooperscooper', 'pooping', 'dookie', 'doodoo', 'caca',
    'fart', 'farted', 'farting', 'fartknocker', 'farty', 'flatulence',
    'piss', 'pissing', 'pissed', 'pisser', 'pisses', 'pisshead', 'pissin', 'pissoff',
    'pee', 'peehole', 'pee-pee',
    'queer', 'queers', 'fag', 'fag1t', 'fagbag', 'faget', 'fagfucker', 'fagg', 'fagg1t',
    'fagged', 'fagging', 'faggit', 'faggitt', 'faggot', 'faggotcock', 'faggs', 'fagit',
    'fagot', 'fagots', 'fags', 'fagt', 'fagtard', 'fagz', 'faig', 'faigs', 'faigt',
    'dyke', 'dykes', 'dike', 'lesbain', 'lesbayn', 'lesbin', 'lesbo', 'lesbos', 'lez',
    'lezbe', 'lezbefriends', 'lezbian', 'lezbians', 'lezbo', 'lezbos', 'lezz', 'lezzian',
    'lezzie', 'lezzies', 'lezzo', 'lezzy', 'bulldike', 'bulldyke', 'butchbabes', 'butchdike',
    'butchdyke', 'dixiedike', 'dixiedyke',
    'homo', 'hom0', 'h0m0', 'h0mo', 'homobangers', 'homodumbshit', 'homoey',
    'trannie', 'tranny', 'transexual', 'transsexual', 'transvestite', 'trisexual',
    'sissy', 'pansies', 'pansy',
    'prostitute', 'hooker', 'hookers', 'brothel', 'redlight',
    'milf', 'dilf',
    'nasty', 'nastyho',
    'skank', 'skankfuck', 'skanky',
    'slime', 'slimeball', 'slimebucket',
    'smut',
    'snatch', 'snatchpatch',
    'suck', 'suckdick', 'sucker', 'suckme', 'suckmyass', 'suckmydick', 'suckmytit',
    'suckoff', 'corksucker', 'cocksuck', 'cocksucked', 'cocksucker', 'cocksucking',
    'cocksucks', 'cocksuka', 'cocksukka',
    'swallow', 'swallower', 'swalow',
    'twat', 'twink', 'twinkie',
    'wank', 'wanker', 'wanking', 'williewanker',
    'boner', 'boners', 'hardon', 'stiffy', 'wood', 'woody',
    'horny', 'horney', 'horniest', 'horndawg', 'horndog',
    'libido', 'lusting', 'lusty',
    'randy',
    'turned on', 'turnon',
    'wetb', 'wetback',
    'climax', 'climaxed', 'climaxing',
    'premature',
    'virgin', 'virginbreaker',
    'condom', 'trojan',
    'lubejob', 'lotion',
    'livesex', 'peepshow', 'peepshpw',
    'hentai', 'ecchi', 'futanari', 'futanary',
    'lolita',
    'taboo',
    'xxx',
    'prick', 'prickhead', 'pric',
    'pube', 'pubic', 'pubiclice',
    'pud', 'pudboy', 'pudd', 'puddboy',
    'puke',
    'quim',
    'schlong',
    'screw', 'screwyou',
    'shag', 'shaggin', 'shagging',
    'shat',
    'spunk', 'spunky',
    'stiffy',
    'strapon',
    'stroke', 'stroking',
    'tampon',
    'tinkle',
    'tongue', 'tongethruster', 'tonguethrust', 'tonguetramp',
    'turd',
    'upskirt',
    'vulva',
    'willy', 'willie',
    'weewee', 'weenie',
    # Additional vulgar/obscene terms
    'douche', 'douche bag', 'douche-fag', 'douchebag', 'douchebags', 'douchewaffle', 'douchey',
    'd0uch3', 'd0uche', 'douch3', 'duche',
    'dipshit', 'dipstick', 'dipship',
    'dumb', 'dumbass', 'dumbasses', 'dumbbitch', 'dumbfuck', 'dumbshit', 'dumshit',
    'dumass',
    'fugly', 'mafugly',
    'gob',
    'gook', 'gook eye', 'gook eyes', 'gookeye', 'gookeyes', 'gookies', 'gooks', 'gooky',
    'g00k',
    'hobag',
    'ho', 'hoare', 'hoer', 'hoes', 'hoor', 'hoore', 'hore', 'h00r', 'h0ar', 'h0r', 'h0re',
    'jackass', 'jackhole', 'jackshit',
    'jerk', 'jerries', 'jerry',
    'junkie', 'junky',
    'knob', 'knobbing', 'knobead', 'knobed', 'knobend', 'knobhead', 'knobjocky', 'knobjokey',
    'knobz',
    'loser', 'looser',
    'lowlife',
    'moron',
    'muff', 'muffdive', 'muffdiver', 'muffindiver', 'mufflikcer',
    'nigger', 'nigga', 'niggah', 'niggaracci', 'niggard', 'niggarded', 'niggarding',
    'niggardliness', 'niggardliness\'s', 'niggardly', 'niggards', 'niggard\'s', 'niggaz',
    'niggerhead', 'niggerhole', 'niggers', 'nigger\'s', 'niggle', 'niggled', 'niggles',
    'niggling', 'nigglings', 'niggor', 'niggur', 'niglet', 'nignog', 'nigr', 'nigra', 'nigre',
    'nig', 'niger', 'nigg', 'nlgger', 'nlggor', 'mgger', 'mggor',
    'paki',
    'perv',
    'pimp', 'pimped', 'pimper', 'pimpjuic', 'pimpjuice', 'pimpsimp', 'popimp',
    'poon', 'poontang', 'puntang',
    'prick', 'prickhead', 'pric',
    'pube', 'pubic', 'pubiclice',
    'pud', 'pudboy', 'pudd', 'puddboy',
    'puke',
    'queer', 'queers',
    'quim',
    'schlong',
    'screw', 'screwyou',
    'shag', 'shaggin', 'shagging',
    'shat',
    'skank', 'skankfuck', 'skanky',
    'slime', 'slimeball', 'slimebucket',
    'smut',
    'snatch', 'snatchpatch',
    'snot',
    'spunk', 'spunky',
    'suck', 'suckdick', 'sucker', 'suckme', 'suckmyass', 'suckmydick', 'suckmytit',
    'suckoff',
    'swallow', 'swallower', 'swalow',
    'tampon',
    'tinkle',
    'tongue', 'tongethruster', 'tonguethrust', 'tonguetramp',
    'turd',
    'twat', 'twink', 'twinkie',
    'upskirt',
    'vulva',
    'wank', 'wanker', 'wanking', 'williewanker',
    'willy', 'willie',
    'weewee', 'weenie',
}

